Feat/ replace redux use with React Query
InseeFr/Bauhaus pull request #547
Opened 2024-01-17 15:13 UTC by PierreVasseur

2024-01-17 15:15 UTC, PierreVasseur commented
Pas encore testé en vrai, je dois installer node version manager pour passer de 18 à 16

2024-01-18 08:05 UTC, EmmanuelDemey commented
Sinon tu peux utiliser l'outil NVM pour faciliter les choses.

2024-01-18 08:06 UTC, EmmanuelDemey commented on app/src/js/applications/operations/series/edition/index.js
> +		queryFn: () => {
idem ;)

2024-01-18 08:07 UTC, EmmanuelDemey commented on app/src/js/applications/operations/series/visualization/index.js
> +			CodesList.getCodesList('CL_FREQ')
idem ;)

2024-02-02 19:00 UTC, EmmanuelDemey requested changes

2024-02-02 19:00 UTC, EmmanuelDemey commented on app/src/js/actions/operations/utils/setup.js
> -export function loadCodesList(notations, dispatch) {
Ne supprimes pas ce code pour le moment, car il est utilisé ailleurs dans l'application en fait.

2024-02-02 19:00 UTC, EmmanuelDemey commented on app/src/js/hooks/hooks.js
> +export function useQueryCodesList(notation) {
Peux tu essayer d'ecrire un petit TU pour ce hook ? :P

2024-02-15 12:05 UTC, closed without merging