Feat/ create hooks useGoBack useGoBackOrReplace and stop using withRouter
InseeFr/Bauhaus pull request #548
Opened 2024-01-17 17:22 UTC by PierreVasseur

2024-01-17 17:24 UTC, PierreVasseur commented
Je suis pas sûr de trouver le code des fonctions goBack et goBackOrReplace actuelles

2024-02-02 18:59 UTC, EmmanuelDemey requested changes

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/document/visualization/index.js
> +export default withRouter(DocumentationVisualizationContainer); // withRouter à supprimer une fois fini
Est-il encore nécessaire ?

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/families/edition/edition.js
> +export default withTitle(withRouter(OperationsFamilyEdition), D.operationsTitle, props => { // withRouter à supprimer une fois fini
item

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/indicators/edition/index.js
> +export default withRouter(OperationsIndicatorsEditionContainer); // withRouter à supprimer une fois fini
idem

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/indicators/visualization/index.js
> +export default withRouter(IndicatorVisualizationContainer); // withRouter à supprimer une fois fini
idem

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/menu/index.js
> +export default withRouter( // withRouter à supprimer une fois fini
idem

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/msd/index.js
> +export default withRouter( // withRouter à supprimer une fois fini
idem

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/msd/pages/sims-creation/index.js
> +export default withRouter(AdvancedSimsCreation); // withRouter à supprimer une fois fini
idem

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/operations/edition/index.js
> +export default withRouter(OperationEditionContainer); // withRouter à supprimer une fois fini
idem

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/operations/visualization/index.js
> +export default withRouter(OperationVisualizationContainer); // withRouter à supprimer une fois fini
idem

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/series/edition/index.js
> +export default withRouter(OperationsSeriesEditionContainer); // withRouter à supprimer une fois fini
idem

2024-02-02 18:59 UTC, EmmanuelDemey commented on app/src/js/applications/operations/series/visualization/index.js
> +export default withRouter(SeriesVisualizationContainer); // withRouter à supprimer une fois fini
idem

2024-02-14 15:13 UTC, closed without merging