Feat/use zod in validation
InseeFr/Bauhaus pull request #562
Opened 2024-02-01 09:15 UTC by PierreVasseur

2024-02-01 14:09 UTC, PierreVasseur commented on app/src/js/applications/operations/families/edition/validation.js
> +	const defaultFields = Object.keys(Family.shape).reduce(
ZodObject plutôt que Family ici non ?

2024-02-01 15:59 UTC, PierreVasseur commented on app/src/js/applications/operations/families/edition/validation.js
> +	prefLabelLg1: z.string({
je pense qu'une chaine vide passe ce contrôle

2024-02-02 18:54 UTC, EmmanuelDemey requested changes

2024-02-02 18:54 UTC, EmmanuelDemey commented on app/src/js/applications/operations/families/edition/validation.js
> +const formatValidation = (ZodObject) => (values) => {
Peux tu mettre cette fonction dans un fichier spécifique au niveau global du module app ? dans un fichier utils/validation.js par exemple ?

2024-02-02 18:54 UTC, EmmanuelDemey commented on app/src/js/applications/operations/families/edition/validation.spec.js
> +		expect(validate({ prefLabelLg1: '', prefLabelLg2: 'prefLabelLg2' })).toEqual({
Je pense que tu dois gérer un TU dans le cas ou ce n'est pas défini et le cas ou c'est une chaine vide.

2024-02-02 18:54 UTC, EmmanuelDemey commented on app/src/js/applications/operations/families/edition/validation.spec.js
> +		expect(validate({ prefLabelLg1: 'prefLabelLg1', prefLabelLg2: '' })).toEqual({
idem

2024-02-02 18:54 UTC, EmmanuelDemey commented on app/src/js/applications/operations/families/edition/validation.spec.js
> +		expect(validate({ prefLabelLg1: '', prefLabelLg2: '' })).toEqual({
idem

2024-02-05 12:46 UTC, PierreVasseur commented on app/src/js/applications/operations/families/edition/validation.js
> +const formatValidation = (ZodObject) => (values) => {
Yes

2024-02-05 13:28 UTC, PierreVasseur commented on app/src/js/applications/operations/families/edition/validation.spec.js
> +		expect(validate({ prefLabelLg1: '', prefLabelLg2: 'prefLabelLg2' })).toEqual({
Ok d'acc

2024-02-12 08:20 UTC, EmmanuelDemey requested changes

2024-02-12 08:20 UTC, EmmanuelDemey commented on app/.env.development
> -REACT_APP_API_BASE_HOST = 'https://gestion-metadonnees-api.developpement2.insee.fr'
Peux tu éviter de comiter ce fichier à chaque fois ? garde la valeur par defaut http://localhost:6969 de mémoire

2024-02-12 08:20 UTC, EmmanuelDemey commented on app/src/js/applications/operations/series/edition/validation.js
> +const Serie = z.object({
Ty ne gère pas la propriété listOfExtraMandatoryFields. C'est voulu ?

2024-02-12 08:20 UTC, EmmanuelDemey commented on app/src/js/utils/validation.js
> +	console.log(fields)
Peux tu supprimer ce console.log ?

2024-02-12 08:20 UTC, EmmanuelDemey commented on app/src/js/utils/validation.js
> +	console.log(ZodError)
Peux tu supprimer ce console.log ?

2024-02-14 08:44 UTC, EmmanuelDemey commented
Cette PR is outdated, and will be reopened based on the main branch

2024-02-14 08:44 UTC, closed without merging