Feat/extend Zod on datasets and distributions
InseeFr/Bauhaus pull request #605
Opened 2024-02-14 14:24 UTC by PierreVasseur

2024-02-16 19:03 UTC, EmmanuelDemey requested changes

2024-02-16 19:03 UTC, EmmanuelDemey commented on app/src/js/applications/datasets/distributions/validation.js
> +const Distribution = z.object({
Peux tu mieux formatter le code pour que cela soit plus facile à lire ?

2024-02-16 19:03 UTC, EmmanuelDemey commented on app/src/js/applications/datasets/distributions/validation.js
> +	idDataset: z.string({required_error: D.mandatoryProperty(D1.datasetsTitle)}),
Pourquoi je n'ai pas de .min ici ?

2024-02-16 19:03 UTC, EmmanuelDemey commented on app/src/js/applications/datasets/datasets/validation.js
> +	creator: z.string({required_error: D.mandatoryProperty(D1.creatorTitle)}),
Pourquoi il n'y a pas de .min dans le block ci-dessous ?

2024-02-19 08:44 UTC, PierreVasseur commented on app/src/js/applications/datasets/distributions/validation.js
> +	idDataset: z.string({required_error: D.mandatoryProperty(D1.datasetsTitle)}),
parce qu'on le choisit dans une liste déroulante donc ça ne peut être que null ou une chaîne non vide

2024-02-19 08:44 UTC, PierreVasseur commented on app/src/js/applications/datasets/datasets/validation.js
> +	creator: z.string({required_error: D.mandatoryProperty(D1.creatorTitle)}),
idem qu'en dessous

2024-02-19 08:44 UTC, PierreVasseur commented on app/src/js/applications/datasets/distributions/validation.js
> +const Distribution = z.object({
yes mais ça fera des lignes un peu à rallonge

2024-02-19 18:51 UTC, EmmanuelDemey approved these changes

2024-02-19 18:51 UTC, merged