set disabled on false
InseeFr/Bauhaus pull request #683
Opened 2024-03-05 15:37 UTC by PierreVasseur

2024-03-05 15:44 UTC, EmmanuelDemey requested changes

2024-03-05 15:44 UTC, EmmanuelDemey commented on packages/structures/src/components/component-detail/edit.js
> +						disabled={false}
Je pense que tu peux supprimer complètement l'attribut?

2024-03-05 15:56 UTC, PierreVasseur commented on packages/structures/src/components/component-detail/edit.js
> +						disabled={false}
oui c'est pas faux

2024-03-06 06:36 UTC, EmmanuelDemey approved these changes

2024-03-06 06:36 UTC, merged