Fix: some wrong error messages when editing
InseeFr/Bauhaus pull request #858
Opened 2024-07-17 16:14 UTC by PierreVasseur

2024-07-17 19:35 UTC, EmmanuelDemey requested changes

2024-07-17 19:35 UTC, EmmanuelDemey commented on src/js/applications/datasets/datasets/edit/validation.js
> +		.nonempty({
@PierreVasseur je vois d'autres min(1) dans le code. Faudrait-il pas tous les changer avec un nonempty ?

2024-07-18 07:37 UTC, PierreVasseur commented on src/js/applications/datasets/datasets/edit/validation.js
> +		.nonempty({
il me semble que nonempty c'est pour les array et min(1) c'est pour les string, normalement le reste du code est cohérent là dessus

2024-07-18 07:50 UTC, EmmanuelDemey approved these changes

2024-07-18 07:50 UTC, merged