Feat: upgrade global error message in Concepts module
InseeFr/Bauhaus pull request #964
Opened 2024-09-19 15:45 UTC by PierreVasseur

2024-09-19 19:25 UTC, EmmanuelDemey approved these changes

2024-09-21 14:25 UTC, EmmanuelDemey requested changes

2024-09-21 14:25 UTC, EmmanuelDemey commented on src/packages/modules-concepts/edition-creation/home.jsx
>  			this.setState({
Peux tu profiter de cette PR, pour utiliser la méthode callback pour le state. Je pense que Sonar nous le préconise. 
Quelque chose comme : 
```
this.setState(state => ({ data: { ...state.data ...}}))
```

2024-09-21 14:25 UTC, EmmanuelDemey commented on src/packages/modules-concepts/edition-creation/home.jsx
>  			this.setState({
Peux tu profiter de cette PR, pour utiliser la méthode callback pour le state. Je pense que Sonar nous le préconise. 
Quelque chose comme : 
```
this.setState(state => ({ data: { ...state.data ...}}))
```

2024-09-21 14:25 UTC, EmmanuelDemey commented on src/packages/modules-concepts/edition-creation/home.jsx
>  			const newData = Object.assign(data, {
Peux tu profiter de cette PR pour utiliser la sytaxe des ... plutot que le Object.assign ?

2024-09-21 14:25 UTC, EmmanuelDemey commented on src/packages/modules-concepts/edition-creation/home.jsx
>  			const newData = Object.assign(data, {
Peux tu profiter de cette PR pour utiliser la sytaxe des ... plutot que le Object.assign ?

2024-09-21 14:25 UTC, EmmanuelDemey commented on src/packages/modules-concepts/edition-creation/home.jsx
>  			this.setState({
https://legacy.reactjs.org/docs/react-component.html#setstate

2024-09-21 14:25 UTC, EmmanuelDemey commented on src/packages/modules-concepts/edition-creation/home.jsx
>  			this.setState({
https://legacy.reactjs.org/docs/react-component.html#setstate

2024-09-21 14:25 UTC, EmmanuelDemey commented on src/packages/modules-concepts/collections/edition-creation/controls.jsx
> +				D={submitting ? D : dict}
Peux tu m'expliquer pourquoi nous avons ce ternaire?

2024-09-23 07:42 UTC, PierreVasseur commented on src/packages/modules-concepts/collections/edition-creation/controls.jsx
> +				D={submitting ? D : dict}
comme demandé dans l'issue, si l'utilisateur vient d'ouvrir la page d'édition alors le message d'erreur n'est pas le même, à partir du moment où il soumet des champs (submitting = true) alors on laisse le message d'avant

2024-09-24 07:08 UTC, EmmanuelDemey approved these changes

2024-09-24 07:08 UTC, merged